In [1]:
import pandas as pd
from ml_models.classifier import Classifier

In [2]:
drug = 'CN1C2=C(C(=O)N(C1=O)C)NC=N2'
coformer = 'C1=CC=C2C=CC=CC2=C1'
properties = ['unobstructed', 'orthogonal_planes', 'h_bond_bridging']

classification = Classifier()
properties = classification.predict_properties(drug, coformer, properties)
print(properties)

{'unobstructed': 1, 'orthogonal_planes': 1, 'h_bond_bridging': 0}

In [3]:
drug = 'CN1C2=C(C(=O)N(C1=O)C)NC=N2'
coformer = 'C1=CC=C2C=CC=CC2=C1'
properties = ['unobstructed', 'h_bond_bridging']

classification = Classifier()
properties = classification.predict_properties(drug, coformer, properties)
print(properties)

{'unobstructed': 1, 'h_bond_bridging': 0}

In [4]:
drug = 'CN1C2=C(C(=O)N(C1=O)C)NC=N2'
coformer = 'C1=CC=C2C=CC=CC2=C1'
properties = ['unobstructed']

classification = Classifier()
properties = classification.predict_properties(drug, coformer, properties)
print(properties)

{'unobstructed': 1}

In [5]:
df = pd.read_csv('data/database_CCDC.csv', header = None)
df['drug'] = 'CN1C2=C(C(=O)N(C1=O)C)NC=N2'
df.rename(columns = {0: 'sequence'}, inplace = True)
df

,sequence,drug
0,CC1(C)C(=O)NC1S(=O)(=O)C1=CC=CC=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2
1,CC1C(=O)NC1S(=O)(=O)C1=CC=CC=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2
2,OC1=CC=CC(O)=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2
3,C(=CC1=CC=NC=C1)C1=CC=NC=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2
4,C1=NC=CC(C2C(C3=CC=NC=C3)C(C3=CC=NC=C3)C2C2=CC...,CN1C2=C(C(=O)N(C1=O)C)NC=N2
...,...,...
4222,O=C1OC2=CC=C(Cl)C=C2NC1=CC(=O)C1=CC=CC=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2
4223,NC(=O)N1C2=CC=CC=C2C=CC2=CC=CC=C21,CN1C2=C(C(=O)N(C1=O)C)NC=N2
4224,CC(C(=O)O)C1=CC=CC(C(=O)C2=CC=CC=C2)=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2
4225,O=C1OC2=CC=CC=C2C2=CC=CC=C12,CN1C2=C(C(=O)N(C1=O)C)NC=N2
4226,N#CC1=C2C=CC=CC2=C(C#N)C2=CC=CC=C12,CN1C2=C(C(=O)N(C1=O)C)NC=N2

In [6]:
df = pd.read_csv('data/database_CCDC.csv', header = None)
df['drug'] = 'CN1C2=C(C(=O)N(C1=O)C)NC=N2'
df.rename(columns = {0: 'sequence'}, inplace = True)
df

,sequence,drug
0,CC1(C)C(=O)NC1S(=O)(=O)C1=CC=CC=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2
1,CC1C(=O)NC1S(=O)(=O)C1=CC=CC=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2
2,OC1=CC=CC(O)=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2
3,C(=CC1=CC=NC=C1)C1=CC=NC=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2
4,C1=NC=CC(C2C(C3=CC=NC=C3)C(C3=CC=NC=C3)C2C2=CC...,CN1C2=C(C(=O)N(C1=O)C)NC=N2
...,...,...
4222,O=C1OC2=CC=C(Cl)C=C2NC1=CC(=O)C1=CC=CC=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2
4223,NC(=O)N1C2=CC=CC=C2C=CC2=CC=CC=C21,CN1C2=C(C(=O)N(C1=O)C)NC=N2
4224,CC(C(=O)O)C1=CC=CC(C(=O)C2=CC=CC=C2)=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2
4225,O=C1OC2=CC=CC=C2C2=CC=CC=C12,CN1C2=C(C(=O)N(C1=O)C)NC=N2
4226,N#CC1=C2C=CC=CC2=C(C#N)C2=CC=CC=C12,CN1C2=C(C(=O)N(C1=O)C)NC=N2

In [7]:
df2 = pd.read_csv('data/database_GAN.csv')
df2['drug'] = 'CN1C2=C(C(=O)N(C1=O)C)NC=N2'
df2.rename(columns = {'smiles': 'sequence'}, inplace = True)
df2

                              sequence                         drug
0           CC1=CC=CC=C1C1=CC=CC(O)=C1  CN1C2=C(C(=O)N(C1=O)C)NC=N2
1               N#CC(=O)NC1=CC=CC=C1Br  CN1C2=C(C(=O)N(C1=O)C)NC=N2
2                        CC1=CNC(=O)N1  CN1C2=C(C(=O)N(C1=O)C)NC=N2
3                NS(=O)(=O)C1=CC=CC=C1  CN1C2=C(C(=O)N(C1=O)C)NC=N2
4                    O=C1NC(=O)C(=O)N1  CN1C2=C(C(=O)N(C1=O)C)NC=N2
...                                ...                          ...
9995                       CS(=O)(=O)O  CN1C2=C(C(=O)N(C1=O)C)NC=N2
9996                           C=C(C)N  CN1C2=C(C(=O)N(C1=O)C)NC=N2
9997    CC1=CC=CC(C)=C1N=NNC1=CC=CC=C1  CN1C2=C(C(=O)N(C1=O)C)NC=N2
9998             CCCOC(=O)C1=CC=CC=C1F  CN1C2=C(C(=O)N(C1=O)C)NC=N2
9999  COC1=CC=C(C2=CC=C(N)C(N)=C2)C=C1  CN1C2=C(C(=O)N(C1=O)C)NC=N2

[10000 rows x 2 columns]

In [8]:
drug = df['drug']
coformer = df['sequence']
properties = ['unobstructed']

classification = Classifier()

def predict_property(row, prop):
    return classification.predict_properties(row['drug'], row['sequence'], [prop])[prop]

# Применяем функцию к каждому ряду DataFrame и сохраняем результат в новом столбце 'properties'
df['unobstructed'] = df.apply(lambda row: predict_property(row, 'unobstructed'), axis=1)
df['h_bond_bridging'] = df.apply(lambda row: predict_property(row, 'h_bond_bridging'), axis=1)
df['orthogonal_planes'] = df.apply(lambda row: predict_property(row, 'orthogonal_planes'), axis=1)

In [9]:
df

,sequence,drug,unobstructed,h_bond_bridging,orthogonal_planes
0,CC1(C)C(=O)NC1S(=O)(=O)C1=CC=CC=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2,0,1,0
1,CC1C(=O)NC1S(=O)(=O)C1=CC=CC=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2,1,1,0
2,OC1=CC=CC(O)=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2,1,1,0
3,C(=CC1=CC=NC=C1)C1=CC=NC=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2,1,0,0
4,C1=NC=CC(C2C(C3=CC=NC=C3)C(C3=CC=NC=C3)C2C2=CC...,CN1C2=C(C(=O)N(C1=O)C)NC=N2,0,0,0
...,...,...,...,...,...
4222,O=C1OC2=CC=C(Cl)C=C2NC1=CC(=O)C1=CC=CC=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2,1,1,0
4223,NC(=O)N1C2=CC=CC=C2C=CC2=CC=CC=C21,CN1C2=C(C(=O)N(C1=O)C)NC=N2,1,1,0
4224,CC(C(=O)O)C1=CC=CC(C(=O)C2=CC=CC=C2)=C1,CN1C2=C(C(=O)N(C1=O)C)NC=N2,0,0,0
4225,O=C1OC2=CC=CC=C2C2=CC=CC=C12,CN1C2=C(C(=O)N(C1=O)C)NC=N2,1,0,0
4226,N#CC1=C2C=CC=CC2=C(C#N)C2=CC=CC=C12,CN1C2=C(C(=O)N(C1=O)C)NC=N2,1,0,0

In [10]:
df.drop_duplicates(subset = 'sequence', inplace = True)

In [11]:
len(set(df['sequence'].values))

4216

In [12]:
df3 = pd.read_csv('dataset.csv', index_col = 0)

In [13]:
df3.drop_duplicates(subset = 'sequence', inplace = True)

In [14]:
df3.to_csv('dataset2.csv')